language: python

python:
  - 3.5

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev
      - python-libxml2

env:
  - VERSION="11.0" LINT_CHECK="1"
  - VERSION="11.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install -r requirements.txt
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
